# Cấu hình ứng dụng
spring:
  application:
    name: jobhunter

  # Cấu hình cơ sở dữ liệu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/jobhunter
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
# Cấu hình tải lên tệp (được comment out để sử dụng giá trị mặc định)
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
